# KAGGLE NOTEBOOK / SCRIPT TEMPLATE
# Instructions:
# 1. Upload `training_data.csv` (generated by export_ml_features.py) to Kaggle.
# 2. Copy and paste this code into a new Kaggle Notebook.
# 3. Ensure the Kaggle Notebook has GPU enabled (Settings -> Accelerator -> GPU T4 x2 or P100).
# 4. Run the code. It will export the trained model as `xgboost_priority_model.pkl`.

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
import joblib

def main():
    print("Loading data...")
    # Adjust this path depending on where Kaggle mounts your uploaded dataset
    dataset_path = "training_data.csv" 
    df = pd.read_csv(dataset_path)

    # 1. Prepare Features (X) and Target (y)
    # Drop IDs and Target columns to create our feature set
    X = df.drop(columns=["event_id", "target_priority", "target_requires_road_closure", "target_event_duration_minutes"])
    
    # We want to predict 'target_priority' (Low, Medium, High, Critical)
    y_raw = df["target_priority"]

    # 2. Encode Categorical Strings into Numbers
    print("Encoding categorical variables...")
    # XGBoost needs categories to be properly typed or encoded. We'll use get_dummies for simplicity.
    categorical_cols = ["event_cause", "corridor", "police_station"]
    X = pd.get_dummies(X, columns=categorical_cols)

    # Encode the target labels (Low=0, Medium=1, High=2, Critical=3)
    le = LabelEncoder()
    y = le.fit_transform(y_raw)
    
    # Save the label encoder so our FastAPI backend knows what 0,1,2,3 mean!
    joblib.dump(le, "label_encoder.pkl")

    # 3. Train / Test Split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 4. Configure XGBoost to use the Kaggle GPU
    print("Configuring XGBoost for GPU...")
    # tree_method="hist" and device="cuda" forces XGBoost to train on the GPU!
    clf = xgb.XGBClassifier(
        tree_method="hist", 
        device="cuda", 
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        random_state=42,
        eval_metric="mlogloss"
    )

    # 5. Train the Model (This will be lightning fast on a Kaggle GPU)
    print("Training model on GPU...")
    clf.fit(X_train, y_train)

    # 6. Evaluate Accuracy
    print("Evaluating model...")
    y_pred = clf.predict(X_test)
    print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    # 7. Export the trained model!
    model_filename = "xgboost_priority_model.pkl"
    joblib.dump(clf, model_filename)
    print(f"Success! Download '{model_filename}' and place it in your backend/app/models folder.")

if __name__ == "__main__":
    main()
